// Minimal stand-in for OpenBLAS's daxpy family, sharing OpenBLAS's real
// exported symbol names and raw wasm32 ABI shapes (see openblas.marshal.json,
// generated by tools/marshal-infer/infer_openblas.sh) so the grate this test
// exercises is driven by the SAME contract-backed inference records real
// OpenBLAS interposition uses, not a hand fixture.
//
// Each body prints a marker on entry: gen_grate.py's generic dispatcher
// (pass_fptr_to_wt in its GRATE_TEMPLATE) has no per-call trace of its own,
// so this is the only way to distinguish "the auto-generated handler
// genuinely marshalled and called this" from a coincidentally-matching
// result produced some other way.
#include <stdio.h>

void cblas_daxpy(int n, double alpha, const double *x, int incx,
                  double *y, int incy) {
    fprintf(stderr, "[libblastoy] cblas_daxpy handler ran n=%d incx=%d incy=%d\n",
            n, incx, incy);
    for (int i = 0; i < n; i++)
        y[i * incy] += alpha * x[i * incx];
}

void daxpy_(const int *n, const double *alpha, const double *x, const int *incx,
            double *y, const int *incy) {
    fprintf(stderr, "[libblastoy] daxpy_ handler ran n=%d incx=%d incy=%d\n",
            *n, *incx, *incy);
    for (int i = 0; i < *n; i++)
        y[i * (*incy)] += (*alpha) * x[i * (*incx)];
}
